#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import signal
import sys

from itertools import cycle
from threading import Event

try:
    import yfinance

    HAS_YFINANCE = True
except ImportError:
    HAS_YFINANCE = False


__program__ = os.path.basename(sys.argv[0])
__version__ = "0.2.8-dev"  # major.minor.revision-channel
__author__ = "Axel McLaren <scm@axml.uk>"


_DEFAULT_DELAY = 5.0  # seconds
_DEFAULT_ROUNDING = 2
_DEFAULT_PADDING = 4
_DEFAULT_COLOR = {
    'background': '#222222',
    'foreground': '#e7e7e7',
    'highlight': '#000000',
    'gain': '#55aa55',
    'loss': '#ff5555'
}
_DEFAULT_OPENER = "xdg-open"

_BASE_WIDTH = 24  # 7-char ticker + 6.2-digit value + 3.2-digit diff + 2 thousand separators

_FORMAT_PLAIN_VAL = "{} {} "
_FORMAT_POLYBAR_VAL = "%{{A2:{} \"{}\":}}%{{B{}}}%{{F{}}}%{{u{}}}%{{+u}}%{{o{}}}%{{+o}} {} %{{-o}}%{{-u}}%{{F-}}%{{B-}}%{{B{}}} {} "
_ZOOM_LEVELS = (
    # day
    {
        'level': 'day',
        'history': ('5d', '1d'),
        'shift': 1,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + "[{}]",
            'polybar': _FORMAT_POLYBAR_VAL + "[%{{F{}}}{}%{{F-}}]%{{B-}}%{{A}}",
        },
    },
    # week
    {
        'level': 'week',
        'history': ('1mo', '1d'),
        'shift': 7,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + "{{{}}}",
            'polybar': _FORMAT_POLYBAR_VAL + "{{%{{F{}}}{}%{{F-}}}}%{{B-}}%{{A}}",
        },
    },
    # month
    {
        'level': 'month',
        'history': ('3mo', '1d'),
        'shift': 30,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + "({})",
            'polybar': _FORMAT_POLYBAR_VAL + "(%{{F{}}}{}%{{F-}})%{{B-}}%{{A}}",
        },
    },
    # year
    {
        'level': 'year',
        'history': ('1y', '1d'),
        'shift': 365,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + "<{}>",
            'polybar': _FORMAT_POLYBAR_VAL + "<%{{F{}}}{}%{{F-}}>%{{B-}}%{{A}}",
        },
    },
    # 5 years
    {
        'level': '5-years',
        'history': ('5y', '3mo'),
        'shift': 20,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + "|{}|",
            'polybar': _FORMAT_POLYBAR_VAL + "|%{{F{}}}{}%{{F-}}|%{{B-}}%{{A}}",
        },
    },
    # price
    {
        'level': 'price',
        'history': ('5d', '5m'),
        'shift': 1,
        'format': {
            'plain': _FORMAT_PLAIN_VAL + ">{}<",
            'polybar': _FORMAT_POLYBAR_VAL + ">%{{F{}}}{}%{{F-}}<%{{B-}}%{{A}}",
        },
    },
)
_QUOTE_URL = "https\\://finance.yahoo.com/quote/"

_VAL_ERROR = "ERROR"
_DIFF_NA = "N/A"


class ConfigError(Exception):
    """ Configuration error class """

    def __init__(self, message):
        sys.stderr.write("%s: configuration error: %s\n" % (__program__, message))

        sys.exit(2)


class Config(object):

    def __init__(self, d):
        for k, v in d.items():
            if isinstance(v, dict):
                v = Config(v)

            setattr(self, k, v)

    def __setattr__(self, k, v):
        if not hasattr(self, k):
            super().__setattr__(k, v)
        else:
            raise RuntimeError("Can't modify read-only config setting: {}".format(k))


class Ticker(object):

    def __init__(self, desc):
        self._starting = False

        self.ticker, self.legend, self.price, self.shares = self.parse(desc)
        self.data = yfinance.Ticker(self.ticker)

        if self.data.history().empty:
            raise ConfigError("failed to load initial ticker history: {}".format(self.ticker))

    def parse(self, desc):
        ti = desc.split(':', 3)

        ticker = ti[0]

        if len(ti) == 1:
            legend = ticker
            price = shares = 0
        elif len(ti) == 2:
            try:
                legend, price = ticker, float(ti[1])
            except ValueError:
                legend, price = ti[1], 0

            shares = 0
        elif len(ti) == 3:
            try:
                legend, price, shares = ticker, float(ti[1]), ti[2]
            except ValueError:
                legend, price, shares = ti[1], ti[2], 0
        elif len(ti) == 4:
            ticker, legend, price, shares = ti

        try:
            price = float(price)
        except ValueError:
            price = 0

        try:
            shares = float(shares)
        except ValueError:
            shares = 0

        return ticker, legend, price, shares

    @property
    def starting(self):
        return self._starting

    @starting.setter
    def starting(self, starting):
        if not isinstance(starting, bool):
            raise TypeError("Invalid starting value")

        self._starting = starting


class Checker(object):

    def __init__(self, tickers, starting_ticker, percent, rounding=_DEFAULT_ROUNDING, padding=_DEFAULT_PADDING, thousand_separator=False, zoom_level=0):
        self.percent = percent
        self.rounding = rounding
        self.padding = padding
        self.k = ',' if thousand_separator else ''
        self.opener = _DEFAULT_OPENER
        self.colors = None
        self.current = None
        self.tickers = None
        self.zoom_levels = None
        self.zoom_current = None
        self.exit = None
        self.skip = False

        self.init(tickers, starting_ticker, zoom_level)

        signal.signal(signal.SIGUSR1, self.cycle)
        signal.siginterrupt(signal.SIGUSR1, False)
        signal.signal(signal.SIGUSR2, self.zoom)
        signal.siginterrupt(signal.SIGUSR2, False)

    @property
    def rounded(self):
        return '{{:{k}.{:d}f}}'.format(self.rounding, k=self.k)

    @property
    def rounded_diff(self):
        return '{{:+{k}.{:d}f}}'.format(self.rounding, k=self.k)

    def padded(self, s):
        padding = _BASE_WIDTH + self.padding - sum(map(len, list(map(str, s))))

        return padding if padding > 0 else 0

    def init(self, tickers, starting_ticker, zoom_level):
        ticker_zero = Ticker(starting_ticker)
        ticker_list = []

        for t in tickers:
            ticker = Ticker(t)

            if ticker.ticker == ticker_zero.ticker:
                ticker.starting = True

            ticker_list.append(ticker)

        if not any(t.starting for t in ticker_list):
            raise ConfigError("{} ticker not found in the passed ticker list".format(ticker_zero.ticker))

        self.tickers = cycle(ticker_list)
        self.zoom_levels = cycle(Config(z) for z in _ZOOM_LEVELS)
        self.exit = Event()

        while True:
            self.zoom()

            if self.zoom_current.level == zoom_level:
                break

        while True:
            self.cycle()

            if self.current.starting:
                break

    def decorate(self, bg, fg, hl, ga, lo):
        colors = {
            'background': bg,
            'foreground': fg,
            'highlight': hl,
            'gain': ga,
            'loss': lo
        }

        # normalize color codes
        colors.update((k, v if v[0] == '#' else '#' + v) for k, v in colors.items())

        self.colors = Config(colors)

    def fetch(self):
        period, interval = self.zoom_current.history
        exchange = self.current.data.info['exchange']

        # account for volatility
        if self.zoom_current.level == 'day' and exchange == 'CCC':
            interval = "5m"

        history = self.current.data.history(period=period, interval=interval)

        if history.empty is True:
            raise ValueError("Historical data not found")
        else:
            val = history['Close'].iloc[-1]

            if self.zoom_current.level == 'price':
                if self.current.price > 0:
                    diff = val - self.current.price

                    if self.percent:
                        diff = diff / self.current.price * 100
                    elif self.current.shares > 0:
                        diff *= self.current.shares
                else:
                    diff = _DIFF_NA
            else:
                periods = self.zoom_current.shift

                # subtract non-trading days
                if self.zoom_current.level == 'year' and exchange != 'CCC':
                    periods -= 115
                # look back 24h
                elif self.zoom_current.level == 'day' and exchange == 'CCC':
                    periods = 288

                diff = getattr(history['Close'], 'pct_change' if self.percent else 'diff')(periods=periods).iloc[-2:].iloc[-1]

                if str(diff) == 'nan':
                    diff = _DIFF_NA
                elif self.percent:
                    diff *= 100

            return val, diff

    def display(self):
        try:
            val, diff = self.fetch()
        except Exception:
            val, diff = _VAL_ERROR, _DIFF_NA

        if isinstance(val, str):
            rounded = val
        else:
            rounded = self.rounded.format(val)

        if isinstance(diff, str):
            formatted_diff = diff
        else:
            formatted_diff = self.rounded_diff.format(diff)

            if self.percent:
                formatted_diff += '%'

        if self.colors is None:
            plain_tmpl = self.zoom_current.format.plain

            output = plain_tmpl.format(self.current.legend, rounded, formatted_diff)
        else:
            if isinstance(diff, str):
                diff_color = self.colors.foreground
            else:
                diff_color = self.colors.gain if diff > 0 else self.colors.loss

            polybar_tmpl = self.zoom_current.format.polybar

            output = polybar_tmpl.format(self.opener,
                                         _QUOTE_URL + self.current.ticker,
                                         self.colors.highlight,
                                         self.colors.foreground,
                                         self.colors.background,
                                         self.colors.background,
                                         self.current.legend,
                                         self.colors.background,
                                         rounded,
                                         diff_color,
                                         formatted_diff)

        sys.stdout.write("{}{:<{padding}}\n".format(output, "", padding=self.padded((self.current.legend, rounded, formatted_diff[1:]))))
        sys.stdout.flush()

    def run(self, delay=_DEFAULT_DELAY, rotate=False):
        while True:
            self.exit.clear()

            while not self.exit.is_set():
                self.display()
                self.exit.wait(delay)

                if rotate and not self.skip:
                    self.cycle()

                self.skip = False

    def cycle(self, *args):
        self.skip = bool(len(args))
        self.current = next(self.tickers)
        self.exit.set()

    def zoom(self, *args):
        self.skip = bool(len(args))
        self.zoom_current = next(self.zoom_levels)
        self.exit.set()


def main():
    if not HAS_YFINANCE:
        raise ConfigError("yfinance (https://github.com/ranaroussi/yfinance) is mandatory for the run")

    parser = argparse.ArgumentParser(description='Stock position tracker for status bars')

    parser.add_argument("-c", "--percent", action='store_true',
                        help="percent change display")
    parser.add_argument("-d", "--delay", type=float,
                        default=_DEFAULT_DELAY,
                        help="delay between checks")
    parser.add_argument("-bg", "--background", type=str,
                        default=_DEFAULT_COLOR['background'],
                        help="background color")
    parser.add_argument("-fg", "--foreground", type=str,
                        default=_DEFAULT_COLOR['foreground'],
                        help="foreground color")
    parser.add_argument("-hl", "--highlight", type=str,
                        default=_DEFAULT_COLOR['highlight'],
                        help="ticker highlight color")
    parser.add_argument("-ga", "--gain", type=str,
                        default=_DEFAULT_COLOR['gain'],
                        help="gain accent color")
    parser.add_argument("-lo", "--loss", type=str,
                        default=_DEFAULT_COLOR['loss'],
                        help="loss accent color")
    parser.add_argument("-k", "--thousand-separator", action='store_true',
                        help="use thousand separator")
    parser.add_argument("-o", "--opener", type=str,
                        default=_DEFAULT_OPENER,
                        help="quote URL opener")
    parser.add_argument("-p", "--plain", action='store_true',
                        help="disable polybar formatting")
    parser.add_argument("-P", "--padding", type=int,
                        default=_DEFAULT_PADDING,
                        help="padding digit number")
    parser.add_argument("-r", "--rounding", type=int, choices=range(0, 14),
                        default=_DEFAULT_ROUNDING,
                        help="decimal rounding")
    parser.add_argument("-R", "--rotate", action='store_true',
                        help="automatically rotate over tickers")
    parser.add_argument("-s", "--one-shot", action='store_true',
                        help="run once and exit (first ticker only)")
    parser.add_argument("-t", "--starting-ticker", type=str,
                        default='',
                        help="starting ticker")
    parser.add_argument("-v", "--version", action='version',
                        version='%(prog)s {0} by {1}'.format(__version__, __author__))
    parser.add_argument("-z", "--zoom-level", type=str, choices=[l['level'] for l in _ZOOM_LEVELS],
                        default=_ZOOM_LEVELS[0]['level'],
                        help="starting zoom level")
    parser.add_argument("ticker", type=str, nargs='+',
                        metavar='TICKER[:LEGEND][:PRICE-PER-SHARE[:SHARES]]',
                        help="ticker list")

    args = parser.parse_args()

    if not args.starting_ticker:
        args.starting_ticker = args.ticker[0]

    checker = Checker(args.ticker, args.starting_ticker, args.percent, args.rounding, args.padding, args.thousand_separator, args.zoom_level)

    if not args.plain:
        checker.decorate(args.background, args.foreground, args.highlight, args.gain, args.loss)
        checker.opener = args.opener

    if not args.one_shot:
        try:
            checker.run(args.delay, args.rotate)
        except KeyboardInterrupt:
            sys.stderr.write("aborted by the operator\n")

            sys.exit(2)
    else:
       checker.fetch()


if __name__ == "__main__":
    main()
